# ======================================================= #
#                                                         #
#                        HelloWorld                       #
#                                                         #
# ======================================================= #

# 这是HelloWorld的配置文件 #
# 由于作者水平太低了，所以什么也没有qwq #

# 请务必下载PlaceholderAPI，因为它是这个插件的前置插件 #
# 下载地址https://www.spigotmc.org/resources/placeholderapi.6245/ #

# 这其实是个测试插件awa #
# 插件版本： 2.7 #
# 请不要随便修改(空空如也改个屁) #
